=== CastroEstudios/Lenguaje-de-Marcas/UT5/AE5.2-Alumnos-1DAMB-DanielCastroCruz/alumnoAC521.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
<xs:element name="alumnos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="20"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="sexo" type="TipoSexo"/>
                            <xs:element name="dni" type="xs:string"/>
                            <xs:element name="direccion" type="xs:string"/>
                            <xs:element name="edad" type="TipoEdad"/>
                            <xs:element name="telefono" type="TipoTelefono"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="TipoEdad">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="16"></xs:minInclusive>
            <xs:maxInclusive value="25"></xs:maxInclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="TipoSexo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M"></xs:enumeration>
            <xs:enumeration value="F"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="TipoTelefono">
        <xs:sequence>
            <xs:element  name="fijo" minOccurs="0" maxOccurs="unbounded">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:pattern value="[9]\d{8}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element  name="movil" minOccurs="0" maxOccurs="unbounded">
                <xs:simpleType>
                    <xs:restriction base="xs:int">
                        <xs:pattern value="[6]\d{8}"></xs:pattern>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

<!-- 1DAMB - Daniel Castro Cruz -->

=== CastroEstudios/Lenguaje-de-Marcas/UT5/AE5.2-Alumnos-1DAMB-DanielCastroCruz/alumnoAC52.xml
<?xml version="1.0" encoding="UTF-8"?>

<alumnos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="alumnoAC521.xsd">

    <alumno>
        <nombre>juanita</nombre>
        <sexo>F</sexo>
        <dni>88748745</dni>
        <direccion>San Agust√≠n 44</direccion>
        <edad>25</edad>
        <telefono>
            <fijo>
                922536599
            </fijo>
            <fijo>
                933225555
            </fijo>
            <movil>
                688956653
            </movil>
            <movil>
                633954565
            </movil>
            <movil>
                645859663
            </movil>
        </telefono>
    </alumno>

    <alumno>
        <nombre>juan</nombre>
        <sexo>M</sexo>
        <dni>28542345</dni>
        <direccion>San Jose 2</direccion>
        <edad>20</edad>
        <telefono>
            <fijo>
                922536599
            </fijo>
            <fijo>
                933225555
            </fijo>
            <movil>
                655989898
            </movil>
        </telefono>
    </alumno>

</alumnos>

<!-- 1DAMB - Daniel Castro Cruz -->
