=== CastroEstudios/Lenguaje-de-Marcas/UT5/AE5.1-Alumnos-1DAMB-DanielCastroCruz/AE5.1-Alumnos-1DAMB-DanielCastroCruz.dtd
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno 
    (nombre, apellidos, direccion, telefonos, procedencia,
    nota-alumno*, informacion-adicional, comentarios)>
    <!ATTLIST alumno ID ID #REQUIRED>
    <!ATTLIST alumno sexo (masculino|femenino) #IMPLIED>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT direccion (via, numero, ciudad)>
        <!ELEMENT via (#PCDATA)>
        <!ELEMENT numero (#PCDATA)>
        <!ELEMENT ciudad (#PCDATA)>
    <!ELEMENT telefonos (telefono+)>
        <!ELEMENT telefono (#PCDATA)>
            <!ATTLIST telefono titular CDATA #REQUIRED>
    <!ELEMENT procedencia (provincia|pais-origen)>
        <!ELEMENT provincia (#PCDATA)>
        <!ELEMENT pais-origen (#PCDATA)>
    <!ELEMENT nota-alumno (#PCDATA|evaluacion)*>
        <!ELEMENT evaluacion (nota)>
        <!ATTLIST evaluacion numero-evaluacion (primera | segunda | final) #REQUIRED>
            <!ELEMENT nota (#PCDATA)>
    <!ELEMENT informacion-adicional (equipo-deportivo?, altura?, aficiones*, ayudado-por*)>
        <!ELEMENT equipo-deportivo (#PCDATA)>
        <!ELEMENT altura (#PCDATA)>
        <!ELEMENT aficiones (#PCDATA)>
        <!ENTITY % alumno-ayudante "alumno">
    <!ELEMENT comentarios (comentario)>
        <!ELEMENT comentario (#PCDATA)>

<!--1DAMB - Daniel Castro Cruz-->

=== CastroEstudios/Lenguaje-de-Marcas/UT5/AE5.1-Alumnos-1DAMB-DanielCastroCruz/AE5.1-Alumnos-1DAMB-DanielCastroCruz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumnos SYSTEM "AE5.1-Alumnos-1DAMB-DanielCastroCruz.dtd">
<alumnos>

    <alumno ID="A0001">
        <nombre>
            Daniel
        </nombre>
        <apellidos>
            Castro Cruz
        </apellidos>
        <direccion>
            <via>
                Calle
            </via>
            <numero>
                12
            </numero>
            <ciudad>
                S/C de Tenerife
            </ciudad>
        </direccion>
        <telefonos>
            <telefono titular="Madre">
                922456655
            </telefono>
            <telefono titular="Padre">
                689556622
            </telefono>
        </telefonos>
        <procedencia>
            <provincia>
                S/C de Tenerife
            </provincia>
        </procedencia>
        <nota-alumno>
            <evaluacion numero-evaluacion="primera">
                <nota>
                    10
                </nota>
            </evaluacion>
        </nota-alumno>
        <informacion-adicional>
            <equipo-deportivo>F.C. CÃ©sar Manrique</equipo-deportivo>
            <altura>186</altura>
            <aficiones>Arte 3D</aficiones>
        </informacion-adicional>
        <comentarios>
            <comentario></comentario>
        </comentarios>
    </alumno>

    <alumno ID="A0002">
        <nombre>
            Pablo
        </nombre>
        <apellidos>
            Castro Cruz
        </apellidos>
        <direccion>
            <via>
                Calle
            </via>
            <numero>
                4
            </numero>
            <ciudad>
                La Laguna
            </ciudad>
        </direccion>
        <telefonos>
            <telefono titular="Madre">
                922456655
            </telefono>
            <telefono titular="Padre">
                689556622
            </telefono>
        </telefonos>
        <procedencia>
            <provincia>
                S/C de Tenerife
            </provincia>
        </procedencia>
        <nota-alumno>
            <evaluacion numero-evaluacion="primera">
                <nota>
                    10
                </nota>
            </evaluacion>
        </nota-alumno>
        <informacion-adicional>
        </informacion-adicional>
        <comentarios>
            <comentario></comentario>
        </comentarios>
    </alumno>

</alumnos>

<!--1DAMB - Daniel Castro Cruz-->
