=== CastroEstudios/Lenguaje-de-Marcas/UT5/AC5.18/AC5.18.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="alumnos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="alumno" minOccurs="0" maxOccurs="unbounded" type="TipoAlumno"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="TipoAlumno">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"></xs:element>
            <xs:element name="edad" type="xs:int"></xs:element>
            <xs:element name="active" type="xs:boolean"></xs:element>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== CastroEstudios/Lenguaje-de-Marcas/UT5/AC5.18/AC5.18.xml
<?xml version="1.0" encoding="UTF-8"?>
<alumnos 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="./AC5.18.xsd">
    <alumno>
        <nombre>Daniel</nombre>
        <edad>21</edad>
        <active>true</active>
    </alumno>
    <alumno>
        <nombre>Antonio</nombre>
        <edad>19</edad>
        <active>false</active>
    </alumno>
</alumnos>
